spring.application.name=Proyecto_Estudio_Tatuaje
server.port=8085

# para mysql 8 bbdd nombbdd
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3307/estudio_tatuajes?useUnicode=true&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=1105

spring.jpa.generate-ddl=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true

jwt.secret.key=MiClaveSecretaTatuajesApp2024LauraElMejorProyecto123456789
jwt.expiration.hours=8

# --- SUBIDA DE ARCHIVOS (SPRING) ---
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# --- SUBIDA DE ARCHIVOS (TOMCAT) ---
server.tomcat.max-http-post-size=50MB
server.tomcat.max-swallow-size=50MB

# CONFIGURACION MAILTRAP (Entorno de Pruebas TFG)
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525

# Credenciales del equipo
spring.mail.username=66b146cbb4c3e9
spring.mail.password=c36609fe83d6f9

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true



# -------CONFIGURACIÓN DE LIMPIEZAS AUTOMÁTICAS ----------

# Limpieza de datos antiguos (presupuestos/citas finalizados)
tatusys.limpieza.datos.cron=0 0 13 * * *
tatusys.limpieza.datos.meses-antiguedad=3

# Limpieza de tokens de contraseña (nueva)
tatusys.limpieza.tokens.cron=0 */30 * * * *

# Configuracin de pools de scheduling
spring.task.scheduling.pool.size=2
spring.task.scheduling.thread-name-prefix=tatusys-limpieza-



